version: "3.7"
services:
  postgres:
    image: postgres:10.0-alpine
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=ChangeMe
      - POSTGRES_DB=balance
    volumes:
      - ./db/001.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "54321:5432"
    networks:
      - db_net

  app:
    image: ${IMAGE_TAG}
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    ports:
      - "0:8080"
    environment:
      - DB_USER=db_user
      - DB_PWD=ChangeMe
      - DB_NAME=balance
    networks:
      - db_net
    restart: on-failure

networks:
  db_net:
    driver: bridge
