version: "3.7"
services:
  postgres:
    image: postgres:10.0-alpine
    container_name: pgs_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=ChangeMe
      - POSTGRES_DB=balance
    volumes:
      - ../db/001.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "54321:5432"
    networks:
      db-net:
        aliases:
          - postgres

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    ports:
      - "0:8080"
    environment:
      - DB_USER=user
      - DB_PWD=ChangeMe
      - DB_NAME=balance
    networks:
      db-net:
        aliases:
          - app
    restart: on-failure

networks:
  db-net:
    driver: bridge
